### ISSUE TITLE
ClassicEra patch 1.14 breaks addon functionality

### ISSUE THREAD

**Issue by JohnVirgin** [itsSinba/SinStats#2]
Hi There,

The newest patch for classic era seems to break much of the apps functionality.

Initial and reload UI commands bring up this error:

```
Message: Interface\AddOns\SinStats\SinStats-3.6.lua:462: Usage: GetSpellCritChance(school)
Time: Tue Oct 12 16:45:52 2021
Count: 338
Stack: Interface\AddOns\SinStats\SinStats-3.6.lua:462: Usage: GetSpellCritChance(school)

Locals:
```

I'm also unable to bring up the settings button at all, and clicking the minimap icon gives me this error:

```
Message: Interface\AddOns\SinStats\SinStatsConfig.lua:282: attempt to call method 'SetBackdrop' (a nil value)
Time: Tue Oct 12 16:46:53 2021
Count: 1
Stack: Interface\AddOns\SinStats\SinStatsConfig.lua:282: attempt to call method 'SetBackdrop' (a nil value)

Locals: 
```

For the stats that do show up on the live tracker, some of seem quite off (hit percentage is in the 50-60% range)

**Comment by itsSinba** [comment]
Hello Jon,

Thanks for reporting. The new patch has indeed broken quite a few things. I'm currently working on a fix that should be up very soon.

**Comment by itsSinba** [comment]
I have just pushed an update (3.6.1) on Curse, WoWi and Wago, whichever you use.

Please let me know if everything works as intended.

Also, just a heads up. I'm planning a new update very soon, with tons of new features for Classic Era, such as SinLive for BCC, as well as many new stats. It will all be available for the 3.7 version. Stay tuned :)

**Comment by JohnVirgin** [comment]
Thanks for the prompt response! I've installed the new update and the settings are now working properly and I can configure which stats to show without any issues.

However, I still receive the spellcritchance error when I come back from a loading screen (although not always). Also, the hit% value is still way off. My spell hit is showing as 62% right now. I've attached a screenshot
![Screen Shot 2021-10-12 at 6 39 33 PM](https://user-images.githubusercontent.com/49659882/137038805-e4d6c4fe-835f-4f47-9ad1-ca6004beab22.png)

**Comment by itsSinba** [comment]
Is the spell crit error exactly the same as before ? Could you send me the log when you get the chance ? I can't seem to reproduce it on my side.

Also, I've attached to this message a zip file containing the addon's main file named SinStats.lua

Could you replace the existing one inside C:\Program Files (x86)\World of Warcraft\_classic_era_\Interface\AddOns\SinStats\
with the new one and tell me if the spell hit works ? You don't need to exit WoW, just overwrite the file then type /reload in-game.

I appreciate the help.


[SinStats.zip](https://github.com/itsSinba/SinStats/files/7334472/SinStats.zip)

**Comment by JohnVirgin** [comment]
It no longer displays crazy values, but is now fixed at 6% (not counting the 6% in brackets to display the hit bump from talents). Swapping out gear that gives hit doesn't change the value at all. This only applies to spell hit, melee hit seems to function normally.

**Comment by JohnVirgin** [comment]
Here are the errors I get when loading in SOMETIMES (e.g. getting on the zep to grom'gol)

```
Message: Interface\AddOns\SinStats\SinStats-3.6.1.lua:486: attempt to concatenate local 'hitChance' (a nil value)
Time: Wed Oct 13 00:27:30 2021
Count: 1
Stack: Interface\AddOns\SinStats\SinStats-3.6.1.lua:486: attempt to concatenate local 'hitChance' (a nil value)

Locals: 
```

The crit chance error hasn't popped up since you provided the new lua, which means I guess the error above is new

**Comment by itsSinba** [comment]
Our friends at Blizzard really made a mess with their new classic era client. It uses a mixture of BCC and Retail APIs, cause why not!

I think it should work with this fix (zip file again, same procedure). Unfortunately, I can't test it as I don't have a high enough level in Classic and the PTR doesn't allow creating level 60s yet. So thanks for testing it out.

[SinStats.zip](https://github.com/itsSinba/SinStats/files/7335373/SinStats.zip)

**Comment by JohnVirgin** [comment]
Yeah, a lot of addons seem to have completely broken as of the new client. We've had some bugs in our raids as well that have caused issues.

Unfortunately, the new file brings us back to absurd values (50-60%). Here's the lua error I get when zoning into new locations:

```
Message: Interface\AddOns\SinStats\SinStats-3.6.1.lua:647: attempt to concatenate local 'hitRangedChance' (a nil value)
Time: Wed Oct 13 08:39:02 2021
Count: 1
Stack: Interface\AddOns\SinStats\SinStats-3.6.1.lua:647: attempt to concatenate local 'hitRangedChance' (a nil value)

Locals: 
```

This pertains to ranged hit chance, I'm not getting any errors associated with spell crit or spell hit now.

I toyed around with my gear a bit to try and give you more information. Not sure if this helps, but with zero gear pieces on my spell hit displays as 6%. In parenthesis next to it is a +6 which I assume is showing added hit from talents since mages have a talent that grants that. However, since I have no gear on and the value outside of the parenthesis also says 6%, perhaps it's being double displayed? If I put on a piece of gear that gives 1% increase in spell hit, it bumps the sinstats value up from 6 to 13%. Adding + 1%hit pieces one at a time always gives me an extra 7% hit on the tracker. I also have gear that has +1% hit as an equip bonus as well as +1% hit as an enchant, and equipping this does indeed give me an extra 14% hit on the tracker.

Since the previous lua file you sent me had the tracker stuck at 6%, I assume now that it just wasn't counting any additional hit from gear, and now the newest version is counting each +1% as +7%. Lastly, just thought I'd add that my warrior displays spell hit properly at 0%.

Not sure how much this helps.

**Comment by itsSinba** [comment]
So hitChance is fixed now and the Ranged hit chance is the one giving an error this time. I will bring a fix to it too.

At least we managed to get the hit chance from talents I suppose. Now is to figure out what they did to hit chance from gear.

I'll get back to you soon.

**Comment by JohnVirgin** [comment]
Awesome, thanks! sorry for bugging you so much with this. This new client has made me realize how much I value having these extra stats on my screen.

**Comment by itsSinba** [comment]
Not at all, I appreciate getting feedback and the help! I'm glad you like the addon!

Here's a new file to replace. 

So it might be a long shot, but I wrote my own Spell Hit API this time. I'm not sure about its accuracy but it's worth a try as it seems like there's not working Blizzard API at the moment. 

Also fixed the Ranged hit chance error - there shouldn't be any more errors now.

[SinStats.zip](https://github.com/itsSinba/SinStats/files/7339683/SinStats.zip)

**Comment by JohnVirgin** [comment]
It worked! I am not getting lua errors when zoning into new places and spell hit is displaying correctly. The only thing i would mention is that your spell hit api is counting the spell hit adds from talents. This is potentially misleading as it tells me my hit is now 14% (+6), when the +6 is already counted in the 14% value.

Either way, great work!

**Comment by itsSinba** [comment]
Awesome! You're right, I'll have to remove the value in parenthesis. I'll push an update in the next few minutes.

Again, thanks for helping out mate
